export const ADD_TODO = "ADD_TODO";

export const EDIT_TODO_TITLE = 'EDIT_TODO_TITLE';

export const FILTER_TODOS = 'FILTER_TODOS';

export const UPDATE_TODO_CHECKED = 'UPDATE_TODO_CHECKED';

export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';

export const REMOVE_TODOS = 'REMOVE_TODOS';

export const REMOVE_TODO = 'REMOVE_TODO';

export const RESET_TODOS = 'RESET_TODOS';